services:
  gateway:
    build: .
    container_name: ayws-gateway
    restart: always
    labels:
      - "traefik.enable=true"
      # SSL için Host kuralı
      - "traefik.http.routers.gateway.rule=Host(`api.ayws.anadoluyazilim.com.tr`)"
      # Giriş noktasını HTTPS (websecure) yapıyoruz
      - "traefik.http.routers.gateway.entrypoints=websecure"
      # Otomatik sertifika alıcısını bağlıyoruz
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      # Uygulamanın içerideki portu
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    networks:
      - proxy

networks:
  proxy:
    external: true
